spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
        - eth0.*
        - VMware.*
        - VPN.*
        - ingress.*
      preferred-networks: 192.168.*,10.10.11.*
  redis:
    password: XXXXXX
    cluster:
      nodes: XXXXXXXXXX
      max-redirects: 6
    lock:
      expire-time: 30
      time-out: 60