spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
        - eth0.*
        - VMware.*
        - VPN.*
        - ingress.*
      preferred-networks: 192.168.*,10.10.11.*
  #      preferred-networks: 182.38.*
  #      preferred-networks: 162.38.*
  redis:
    host: XXXXXXXX
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 50
        max-wait: -1ms
    lock:
      expire-time: 30
      time-out: 60