spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
        - eth0.*
        - VMware.*
        - VPN.*
        - ingress.*
      preferred-networks: 192.168.*,10.10.11.*
  redis:
    #password: Chenyx1q2w3e4r5t
    lock:
      expire-time: 30
      time-out: 60
    host: 192.168.211.129
    port: 6379


